2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/stephenmarcou/Documents/ETH Zurich/Semester 2/AI Center Projects in Machine Learning/pmlr25-lpn/src/wandb/run-20250508_125310-xfw3pm5m/logs/debug.log
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/stephenmarcou/Documents/ETH Zurich/Semester 2/AI Center Projects in Machine Learning/pmlr25-lpn/src/wandb/run-20250508_125310-xfw3pm5m/logs/debug-internal.log
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1715c0c40>
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:init():852] calling init triggers
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:init():893] starting backend
2025-05-08 12:53:10,672 INFO    MainThread:55755 [wandb_init.py:init():897] sending inform_init request
2025-05-08 12:53:10,680 INFO    MainThread:55755 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 12:53:10,680 INFO    MainThread:55755 [wandb_init.py:init():907] backend started and connected
2025-05-08 12:53:10,702 INFO    MainThread:55755 [wandb_run.py:_label_probe_notebook():1369] probe notebook
2025-05-08 12:53:10,703 INFO    MainThread:55755 [wandb_init.py:init():1002] updated telemetry
2025-05-08 12:53:10,854 INFO    MainThread:55755 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-05-08 12:53:11,717 INFO    MainThread:55755 [wandb_init.py:init():1101] starting run threads in backend
2025-05-08 12:53:11,826 INFO    MainThread:55755 [wandb_run.py:_console_start():2566] atexit reg
2025-05-08 12:53:11,827 INFO    MainThread:55755 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-05-08 12:53:11,827 INFO    MainThread:55755 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-05-08 12:53:11,827 INFO    MainThread:55755 [wandb_run.py:_redirect():2506] Redirects installed.
2025-05-08 12:53:11,829 INFO    MainThread:55755 [wandb_init.py:init():1147] run started, returning control to user process
2025-05-08 13:05:19,847 INFO    MainThread:55755 [wandb_run.py:_finish():2314] finishing run stephen-marcou-eth-z-rich/deterministic_lpn4sine_cf_maml/xfw3pm5m
2025-05-08 13:05:19,859 INFO    MainThread:55755 [jupyter.py:save_history():477] not saving jupyter history
2025-05-08 13:05:19,859 INFO    MainThread:55755 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-05-08 13:05:19,860 INFO    MainThread:55755 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-05-08 13:05:19,861 INFO    MainThread:55755 [wandb_run.py:_atexit_cleanup():2531] got exitcode: 0
2025-05-08 13:05:19,865 INFO    MainThread:55755 [wandb_run.py:_restore():2513] restore
2025-05-08 13:05:19,866 INFO    MainThread:55755 [wandb_run.py:_restore():2519] restore done
2025-05-08 14:21:12,236 WARNING MsgRouterThr:55755 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/miniconda3/envs/lpn_py310/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/opt/miniconda3/envs/lpn_py310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/miniconda3/envs/lpn_py310/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/lpn_py310/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/miniconda3/envs/lpn_py310/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-08 14:21:12,284 INFO    MsgRouterThr:55755 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 6 handles.
